const BASENAME = "APP/"
export default {
    AUTHME: BASENAME + "AUTHME",
    LOGIN: BASENAME + "LOGIN",
    REGISTER: BASENAME + "REGISTER",
    SET_USER: BASENAME + "SET_USER",
    SET_TOKEN: BASENAME + "SET_TOKEN",
    SET_RAW_REGION: BASENAME + "SET_RAW_REGION",
    SET_REGION_ID: BASENAME + "SET_REGION_ID",
    SET_POSITION: BASENAME + "SET_POSITION",
    REQUEST_REGION: BASENAME + "REQUEST_REGION",
    SAVE_EDITS: BASENAME + "SAVE_EDITS",
    INIT: BASENAME + "INIT"
}
