const BASENAME = "APP/"
export default {
    AUTHME: BASENAME + "AUTHME",
    LOGIN: BASENAME + "LOGIN",
    REGISTER: BASENAME + "REGISTER",
    SET_USER: BASENAME + "SET_USER",
    SET_TOKEN: BASENAME + "SET_TOKEN",
    SAVE_EDITS: BASENAME + "SAVE_EDITS",
}
