const BASENAME = "APPEAL/"
export default {
    REQUEST: BASENAME + "REQUEST",
    REQUEST_MINE: BASENAME + "REQUEST_USER",
    REQUEST_USER: BASENAME + "REQUEST_MINE",
    SET_MINE: BASENAME + "SET_MINE",
    SET_USER_MINE: BASENAME + "SET_USER_MINE",
    SET_USER: BASENAME + "SET_USER",
    CREATE: BASENAME + "CREATE",
    GET: BASENAME + "GET",
    SET: BASENAME + "SET",
    SET_CURRENT: BASENAME + "SET_CURRENT",
    SET_LATEST: BASENAME + "SET_LATEST",
    SET_FILTER: BASENAME + "SET_FILTER",
}
