const BASENAME = "APPEAL/"
export default {
    REQUEST: BASENAME + "REQUEST",
    CREATE: BASENAME + "CREATE",
    GET: BASENAME + "GET",
    SET: BASENAME + "SET",
    SET_CURRENT: BASENAME + "SET_CURRENT",
    SET_LATEST: BASENAME + "SET_LATEST",
}
