const BASENAME = "NEWS/"
export default {
    REQUEST: BASENAME + "REQUEST",
    REQUEST_LOCAL: BASENAME + "REQUEST_LOCAL",
    SET_CURRENT: BASENAME + "SET_CURRENT",
    SET: BASENAME + "SET",
    SET_LOCAL: BASENAME + "SET_LOCAL",
}
