const BASENAME = "TENDER/"
export default {
    REQUEST: BASENAME + "REQUEST",
    REQUEST: BASENAME + "REQUEST",
    GET: BASENAME + "GET",
    SET_CURRENT: BASENAME + "SET_CURRENT",
    SET: BASENAME + "SET",
    ADD_COMMENT: BASENAME + "ADD_COMMENT",
    VOTE: BASENAME + "VOTE",
    SET_VOTES: BASENAME + "SET_VOTES",
}
